// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
insert into audit_logs (
	event_type,
	rule_id,
	task_id,
	details
) values (
	$1, $2, $3, $4
)
`

type CreateAuditLogParams struct {
	EventType string      `json:"event_type"`
	RuleID    pgtype.UUID `json:"rule_id"`
	TaskID    pgtype.UUID `json:"task_id"`
	Details   []byte      `json:"details"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.EventType,
		arg.RuleID,
		arg.TaskID,
		arg.Details,
	)
	return err
}

const createReminderRule = `-- name: CreateReminderRule :exec
insert into reminder_rules (
	task_id,
	name,
	days,
	trigger_type,
	offset_minutes
) values (
	$1, $2, $3, $4, $5
)
`

type CreateReminderRuleParams struct {
	TaskID        pgtype.UUID `json:"task_id"`
	Name          string      `json:"name"`
	Days          int32       `json:"days"`
	TriggerType   string      `json:"trigger_type"`
	OffsetMinutes int32       `json:"offset_minutes"`
}

func (q *Queries) CreateReminderRule(ctx context.Context, arg CreateReminderRuleParams) error {
	_, err := q.db.Exec(ctx, createReminderRule,
		arg.TaskID,
		arg.Name,
		arg.Days,
		arg.TriggerType,
		arg.OffsetMinutes,
	)
	return err
}

const createTask = `-- name: CreateTask :exec
insert into tasks (
	title,
	description,
	due_at,
	status
) values (
	$1, $2, $3, $4
)
`

type CreateTaskParams struct {
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	DueAt       pgtype.Timestamp `json:"due_at"`
	Status      string           `json:"status"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.Exec(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.DueAt,
		arg.Status,
	)
	return err
}

const deleteReminderRule = `-- name: DeleteReminderRule :exec
DELETE FROM reminder_rules WHERE id = $1
`

func (q *Queries) DeleteReminderRule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReminderRule, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getAuditLog = `-- name: GetAuditLog :one
SELECT id, event_type, rule_id, task_id, details, created_at FROM audit_logs WHERE id = $1
`

func (q *Queries) GetAuditLog(ctx context.Context, id pgtype.UUID) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLog, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.RuleID,
		&i.TaskID,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogs = `-- name: GetAuditLogs :many
SELECT id, event_type, rule_id, task_id, details, created_at FROM audit_logs WHERE task_id = $1
`

func (q *Queries) GetAuditLogs(ctx context.Context, taskID pgtype.UUID) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogs, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.RuleID,
			&i.TaskID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReminderRules = `-- name: GetReminderRules :many
SELECT id, task_id, name, days, trigger_type, offset_minutes, is_active, created_at, updated_at FROM reminder_rules WHERE task_id = $1
`

func (q *Queries) GetReminderRules(ctx context.Context, taskID pgtype.UUID) ([]ReminderRule, error) {
	rows, err := q.db.Query(ctx, getReminderRules, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReminderRule{}
	for rows.Next() {
		var i ReminderRule
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Name,
			&i.Days,
			&i.TriggerType,
			&i.OffsetMinutes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, title, description, due_at, status, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DueAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasks = `-- name: GetTasks :many
SELECT id, title, description, due_at, status, created_at, updated_at
FROM tasks
WHERE
($1::text IS NULL OR status = $1)
    AND ($2::timestamp IS NULL OR due_at >= $2)
    AND ($3::timestamp IS NULL OR due_at <= $3)
ORDER BY due_at ASC
`

type GetTasksParams struct {
	Column1 string           `json:"column_1"`
	Column2 pgtype.Timestamp `json:"column_2"`
	Column3 pgtype.Timestamp `json:"column_3"`
}

func (q *Queries) GetTasks(ctx context.Context, arg GetTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasks, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DueAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReminderRule = `-- name: UpdateReminderRule :exec
UPDATE reminder_rules
SET
    name = COALESCE($2, name),
    days = COALESCE($3, days),
    trigger_type = COALESCE($4, trigger_type),
    offset_minutes = COALESCE($5, offset_minutes),
    is_active = COALESCE($6, is_active),
    updated_at = NOW()
WHERE id = $1
`

type UpdateReminderRuleParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Days          int32       `json:"days"`
	TriggerType   string      `json:"trigger_type"`
	OffsetMinutes int32       `json:"offset_minutes"`
	IsActive      bool        `json:"is_active"`
}

func (q *Queries) UpdateReminderRule(ctx context.Context, arg UpdateReminderRuleParams) error {
	_, err := q.db.Exec(ctx, updateReminderRule,
		arg.ID,
		arg.Name,
		arg.Days,
		arg.TriggerType,
		arg.OffsetMinutes,
		arg.IsActive,
	)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    due_at = COALESCE($4, due_at),
    status = COALESCE($5, status),
    updated_at = NOW()
WHERE id = $1
`

type UpdateTaskParams struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	DueAt       pgtype.Timestamp `json:"due_at"`
	Status      string           `json:"status"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DueAt,
		arg.Status,
	)
	return err
}
